# Generated by Django 4.1.4 on 2022-12-16 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Post',
            new_name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_type',
        ),
    ]
