# Generated by Django 4.1.4 on 2023-01-08 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_story'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Story',
        ),
    ]
