# Generated by Django 4.1.4 on 2022-12-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_profile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follwing_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follwer', models.CharField(max_length=100)),
                ('follwing', models.CharField(max_length=100)),
            ],
        ),
    ]
