# Generated by Django 4.1.4 on 2022-12-21 14:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0005_follwing_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follownig',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
